logging:
    config: classpath:logback.xml
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://127.0.0.1:8093/xxl-job-admin
        executor:
            address: ''
            appname: s1gn-stock-job
            ip: ''
            logpath: ./logs
            logretentiondays: 30
            port: 9999
